# Generated by Django 5.1.6 on 2025-03-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_datecreated_alter_task_lastmodified'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='username',
            field=models.CharField(default='jack', max_length=255),
            preserve_default=False,
        ),
    ]
