# Generated by Django 5.1.6 on 2025-03-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='numOfTasks',
            field=models.IntegerField(default=0),
        ),
    ]
