# Generated by Django 5.1.6 on 2025-03-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_numoftasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
