# Generated by Django 5.2 on 2025-04-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_sharedwith'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedwith',
            name='id',
        ),
        migrations.AddField(
            model_name='sharedwith',
            name='pk',
            field=models.CompositePrimaryKey('user_id', 'todo_id', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
