# Generated by Django 5.2 on 2025-04-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_remove_sharedwith_id_sharedwith_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedwith',
            name='pk',
        ),
        migrations.AddField(
            model_name='sharedwith',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
