# Generated by Django 5.2 on 2025-04-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_remove_sharedwith_pk_sharedwith_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedwith',
            name='access',
            field=models.CharField(default='r', max_length=1),
        ),
    ]
