# Generated by Django 5.2 on 2025-04-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_sharedwith_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedwith',
            name='access',
            field=models.CharField(choices=[('R', 'Read'), ('W', 'Write')], default='R', max_length=1),
        ),
    ]
